### PR TITLE
Unravel enums to strings

### PR DESCRIPTION
**Pull request by zbroyar**

### CODE REVIEW

**Comment by zbroyar** [comment]
Hi there.

Friendly bump on this.

**Comment by darioteixeira** [comment]
This PR got "a bit" messy with the PPX commits mixed in. Would you mind opening a new one or cleaning it up?

**Comment by zbroyar** [comment]
Can I just recommend you to merge this stuff altogether? Currently, I
use my master branch in production over pretty big datasets (tens of
millions rows) and everything work pretty well.

**Comment by darioteixeira** [comment]
I don't have much time at the moment for a careful vetting of the code, but if you can vouch for it, then great! Also, does the original author of the PG'OCaml PPX want the code to be merged already? I was under the impression that it was still in beta...

**Comment by zbroyar** [comment]
Let me ask them directly :-)

**Comment by remyzorg** [comment]
@darioteixeira @zbroyar 

What is the state of this work ?

**Comment by zbroyar** [comment]
Sorry for delay.

Nothing changed. I'm still using master branch of my fork. Still has no issues.
@tizoc, @eras, any objections to committing your work into the main repo?

**Comment by tizoc** [comment]
Hi @zbroyar. I haven't really used the code in these commits, so I can't really comment much on it. I instead wrote a new ppx extension that takes a slightly different approach, you can see it here: https://github.com/tizoc/ppx_pgsql

I haven't released it to the opam package repository, but I have been using it for a while already without problems.

If it were me, I would just keep ppx out of this project and as a separate thing just to not complicate @darioteixeira's life.

There is a lot of stuff going in this PR, I'm not even sure what is being added, sorry :/

**Pull request closed without merging**
