### PR TITLE
Unravel enums to strings

### PR DESCRIPTION
**Pull request by zbroyar**
This allows to unravel enum types (create type ... as enum ...). Please, merge :-)

### CODE REVIEW

**Comment by darioteixeira** [comment]
Thanks for the patch! I'll take a look at it over the weekend.

**Comment by darioteixeira** [comment]
Any particular reason why the patch only handles insertions/updates?

**Comment by zbroyar** [comment]
Nope, my bad. I dismiss this PR and will get back with another one soon.

Sorry.

**Comment by malthe** [comment]
@zbroyar – bump :-)

**Comment by zbroyar** [comment]
@malthe, there was some discussions in comments under different PRs so I got lost a little bit :-)
Appropriate commit was made Sep 19, 2016 but I don't remember what exactly prevented me from creating another PR.

Right now I'm using my own fork which includes enums-to-strings expansions and ppx. It's in production for more than a year already. You can find it here: https://github.com/zbroyar/pgocaml

@darioteixeira, shall I create another PR with enums and PPX? It's looks pretty stable to me :-)

**Pull request closed without merging**
