### PR TITLE
add OID for citext (case insensitive text)

### PR DESCRIPTION
**Pull request by pwbs**
modified:   src/PGOCaml_generic.ml

### CODE REVIEW

**Comment by darioteixeira** [comment]
Where did you get the magic number (123107) for this type from?

**Comment by pwbs** [comment]
From 
`Camlp4: Uncaught exception: PGOCaml_generic.Make(Thread).Error ("PGOCaml: unknown type for OID 123107")`

which I've just realised is quite a bad source...

**Comment by pwbs** [comment]
I can't find another source! :(
Does the fact that the "extension" comes from <http://www.postgresql.org/docs/current/static/citext.html> mean that that OID will be the same for everyone?

**Comment by pwbs** [comment]
Aaaaaaah... That OID is not the same for everyone!! So this doesn't work. :(

**Comment by pwbs** [comment]
@darioteixeira would you have any suggestion on how to solve this?

**Comment by darioteixeira** [comment]
In `pa_pgsql.ml` there's a somewhat related hack for the `hstore` type.  Basically you have to create a special query to Postgresql's system catalogues (mainly `pg_type` and `pg_attribute`).  I haven't looked closely at `citext` in particular, but I reckon a similar solution could apply.

**Comment by darioteixeira** [comment]
(Incidentally, fixing the current mechanism for determining the types is on my list of features-for-future-pgocaml-which-I-had-the-time-to-be-working-on.)

**Comment by pwbs** [comment]
@darioteixeira thank you, you have confirmed what I ended up suspecting.

I'm closing this PR. I hope a new one will be opened soon...

**Comment by pwbs** [comment]
Reopening this PR to avoid creating a new one without the history... I've `git push -f`ed.

This time, I'm guessing it should be ok! :-)

**Comment by darioteixeira** [comment]
Looks fine.  Thanks for your contribution!

**Pull request merged**
