### PR TITLE
Pcre tests + fix little bug

### PR DESCRIPTION
**Pull request by rgrinberg**
I've added some preliminary tests before switching to ocaml-re and caught a
little bug as well.

oUnit as was added as a test dependency, is that ok?

### CODE REVIEW

**Comment by rgrinberg** [comment]
Also, i'm not exactly sure about the last commit? Was it really intended to match `.` more than once?

Seems like a mistake.

**Comment by darioteixeira** [comment]
Yes, at first glance there seems to be indeed a couple of problems with that regexp: parsing a generic character instead of an actual point, and parsing any number of them instead of just one. But to be sure, I'll page @vbmithr, who has contributed the support for `point` type: Vincent, can you comment on the regular expression used to parse points?  Could there be a mistake, or is this as intended?

**Comment by rgrinberg** [comment]
ping @vbmithr

**Comment by rgrinberg** [comment]
Looks like @vbmithr is on vacation :)

@darioteixeira IMO this should be merged because now that I look at it again it's clearly a mistake. Adding the space matching around `float_pat` doesn't make any sense if the `.` was intentional.

**Comment by vbmithr** [comment]
On 06/12/2015 10:58, Rudi Grinberg wrote:
> Looks like @vbmithr <https://github.com/vbmithr> is on vacation :)
> 
> @darioteixeira <https://github.com/darioteixeira> IMO this should be
> merged because now that I look at it again it's clearly a mistake.
> Adding the space matching around |float_pat| doesn't make any sense if
> the |.| was intentional.
> 

Let me look at this!

Vincent

**Comment by vbmithr** [comment]
Thanks @rgrinberg for the tests! Yeah, it obviously looks it's a mistake. I thinks this can be merged!

**Comment by rgrinberg** [comment]
Rebased

**Comment by darioteixeira** [comment]
Merged.  And thanks for the patch!

**Pull request merged**
