### PR TITLE
Dunify

### PR DESCRIPTION
**Pull request by chrismamo1**
This PR migrates the build system to Dune, and properly registers the PPX as a `migrate-parsetree` driver.

It probably should not be merged for several months at least, as it drops support for the camlp4 extension entirely.

### CODE REVIEW

**Comment by NightBlues** [comment]
Is it currently posible to use pgocaml.ppx from dune without this PR merged?

**Comment by chrismamo1** [comment]
> Is it currently posible to use pgocaml.ppx from dune without this PR merged?

Yes, `pgocaml.ppx` is currently built as an omp driver, so it should work fine with dune.

**Comment by NightBlues** [comment]
I seems to be a noob question, but what dune configuration should I use? I've tried something like
```
(library
  (name mydb)
  (libraries pgocaml pgocaml.ppx)
  (preprocess (pps pgocaml.ppx)))
```
But it's not working :(

**Comment by chrismamo1** [comment]
I just tried with my own minimal toy project and a similar Dune file to the one you just provided, and indeed it does not seem to work as expected off of `master`. For now, I'd recommend using this branch.

```
opam pin add pgocaml https://github.com/chrismamo1/pgocaml.git#dunify
```

I'm not sure what's preventing `master` from being used as a proper PPX driver with Dune, I suspect there's a missing flag in the `META` file.

Also, you don't need to specify `pgocaml.ppx` in the `libraries` field. All it provides is the PPX rewriter.

**Comment by NightBlues** [comment]
With pinning this branch its working! Also pgsql.object feature is very convenient! Thank you.

**Comment by chrismamo1** [comment]
No problem! Thank you for letting us know about these issues.

**Comment by swuecho** [comment]
```
#=== ERROR while compiling pgocaml.3.2 ========================================#
# context     2.0.4 | macos/x86_64 | ocaml-base-compiler.4.08.0 | pinned(git+https://github.com/chrismamo1/pgocaml.git#dunify#690b398e)
# path        ~/.opam/4.08.0/.opam-switch/build/pgocaml.3.2
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build
# exit-code   1
# env-file    ~/.opam/log/pgocaml-50099-c61e7b.env
# output-file ~/.opam/log/pgocaml-50099-c61e7b.out
### output ###
# [...]
# Use Stdlib instead.
# 
# If you need to stay compatible with OCaml < 4.07, you can use the 
# stdlib-shims library: https://github.com/ocaml/stdlib-shims
# File "src/PGOCaml.ml", line 30, characters 21-43:
# 30 |   type out_channel = Pervasives.out_channel
#                           ^^^^^^^^^^^^^^^^^^^^^^
# Error (alert deprecated): module Stdlib.Pervasives
# Use Stdlib instead.
# 
# If you need to stay compatible with OCaml < 4.07, you can use the 
# stdlib-shims library: https://github.com/ocaml/stdlib-shims
```

no compatible with 4.08.0 yet?

**Comment by zbroyar** [comment]
On my macbook "opam pin" failed with the following error:

```
#=== ERROR while compiling pgocaml.3.2 ========================================#
# context     2.0.4 | macos/x86_64 | ocaml-base-compiler.4.07.0 | pinned(git+https://github.com/chrismamo1/pgocaml.git#dunify#690b398e)
# path        ~/.opam/4.07.0/.opam-switch/build/pgocaml.3.2
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build
# exit-code   1
# env-file    ~/.opam/log/pgocaml-59013-c61e7b.env
# output-file ~/.opam/log/pgocaml-59013-c61e7b.out
### output ###
#    genconfig src/PGOCaml_config.ml (exit 1)
# (cd _build/default/src && ./genconfig.sh) > _build/default/src/PGOCaml_config.ml
# sed: illegal option -- s
# usage: sed script [-Ealn] [-i extension] [file ...]
#        sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
# sed: 1: "PGOCaml_config.ml.in": extra characters at the end of P command

```

**Comment by Et7f3** [comment]
Why did you add dependencies on base/batteries (that is not listed in pgocaml.opam). From what I have seen you have remove `open PGOCaml_aux` that contain `String.start_with` and include a whole library for a function ... maybe I am wrong but seem compile fine without batterie and with PGOCaml_aux

**Comment by zbroyar** [comment]
Hi all,

I stole a dune stuff from "dunify" branch of @chrismamo1's clone, added them to the base repo of @darioteixeira and did some polishing.

It works for me now if I build the library by hands with "dune build --profile release" to ignore warnings.

"Works" here means I can write in my project something like
```
(library
 (name storage)
 (libraries mybase pgocaml pgocaml.ppx)
 (preprocess (pps pgocaml.ppx)))
```
and dune build my library.

Repo is here: [zbroyar/pgocaml](https://github.com/zbroyar/pgocaml)

**Comment by darioteixeira** [comment]
Thank you @chrismamo1 and @zbroyar for your work on Dunefying PGOCaml. I would like to merge @zbroyar master into my master (there's a few minor tweaks I would like to do afterwards). Are you okay with this plan, @zbroyar?

I'm also pinging @jrochel and @vouillon because I reckon they'd want to be in the loop.

**Comment by zbroyar** [comment]
@darioteixeira, yes, completely. Please, proceed :-)

**Comment by fakenickels** [comment]
I'm so happy this is happening!

**Comment by chrismamo1** [comment]
Closing this, since it's been obviated by @zbroyar 's work.

**Pull request closed without merging**
