### PR TITLE
Add support for PostgreSQL types: UUID, JSONB

### PR DESCRIPTION
**Pull request by johnlepikhin**

### CODE REVIEW

**Comment by darioteixeira** [comment]
I've been thinking about integrating json/jsonb types myself. My doubts concern their OCaml representation.  You've chosen `string`, which is of course more flexible, but I've been wondering if it wouldn't be better to take the plunge and make PG'OCaml depend on Yojson.  Any thoughts?

**Comment by rgrinberg** [comment]
What about users who prefer to use jsonm over yojson?

**Comment by darioteixeira** [comment]
> What about users who prefer to use jsonm over yojson?

Yes, they are the reason I said `string` is more flexible. Ideally, all these JSON libraries would share a common `type json`.  Perhaps they already do.  Besides Yojson and Jsonm, what other JSON libraries are commonly used?

**Comment by rgrinberg** [comment]
I'm not aware of any other json libraries in use. Yojson and Jsonm do not use the same type. They both use a polymorphic variant but the variant names are slightly different.

**Comment by darioteixeira** [comment]
In the meantime I've taken a look at Jsonm, and it's not compatible with Yojson and may never be.  Oh well, I reckon `string` wins.  I'll merge this request.

**Pull request merged**
